mintel/helm-charts

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_capabilities.tpl
charts/standard-application-stack/templates/ingress.yaml
charts/standard-application-stack/values.yaml

The Ingress currently doesn't render for `networking.k8s.io/v1` correctly. This should fix it.
- Drop support for Kubernetes < v1.21, per @nabadger 
- Render service and port correctly for Ingress v1.
- Makes use of the `ingressClass` field instead of the `kubernetes.io/ingress.class` annotation where possible.
- Stop setting the ingress class to haproxy by default. We only have one ingress class (haproxy) and the controller is set to handle ingresses with no class set via the `--watch-ingress-without-class` flag. (What we really need to do is create an IngressClass resource for haproxy with the `ingressclass.kubernetes.io/is-default-class` annotation set. That's the canonical way to have a default ingress class.)

Refactor Ingress; drop support for Kubernetes < v1.21

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/pod-monitor.yaml

The `main-` prefix is added when you have a `Service` , was as `PodMonitor` should use the named port on the pod only.
Also made it an option to override via `metrics` settings.

Fix PodMonitor port for main deployment

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/values.yaml

- fix: Corrected enable to enabled under kubelock in values.yaml
- docs: Update version to 3.2.2 in CHANGELOG.md
- docs: Update Chart.yaml with new chart version 3.2.2

BUGFIX: Kubelock variable

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/templates/deployment-aws-es-proxy.yaml
charts/standard-application-stack/templates/deployment-celery-exporter.yaml
charts/standard-application-stack/templates/deployment-mysqldexporter.yaml
charts/standard-application-stack/templates/deployment-postgresqlexporter.yaml

- feat: Added annotation to skip (forthcoming) opa check for security context to deployment-aws-es-proxy.yaml,deployment-celery-exporter.yaml,deployment-mysqldexporter.yaml and deployment-postgresqlexporter.yaml
- docs: Update version to 3.3.0 in CHANGELOG.md
- docs: Update Chart.yaml with new chart version 3.3.0

CPT-85: Add OPA Security context check

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/cronjobs.yaml

Defaults to false, but when set to true, it will pull in the `runAsUser: 1000`, which is defined as a default in values.yaml

Added option for cronjobs to inherit base podSecurityContext

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/values.yaml

Adds support for running GitSync as a sidecar.
Note, it's easier to be explicit about git-sync args here (hence the specific `repo` , `dest` options etc) rather than allow any args to be passed in.  Mostly because the `root` is a volume mount that we handled automatically (so we need to know the name of `root`).
---
Also simplified the logic around writing volumes. 
Does mean we can end up with:
```yaml
volumes:
<nothing here>
```
but k8s ignores this.

Add gitsync sidecar support

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_oauth-proxy.tpl
charts/standard-application-stack/values.yaml

Adds extra options to config the oauth2 proxy
`scope` and `user-id-claim` might be useful in the future, so added explicit options for now.
Added `env` to allow any other custom option passed in, although be wary that this can conflict with some of the explict args that we set, such as `scope` or `allowedgroups`.

Add extra configuration support to oauth2-proxy

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/templates/ingress.yaml
charts/standard-application-stack/tests/ingress_test.yaml

If neither `ingress.specificTlsHostsYaml` nor `global.ingressTLSSecrets` are specified, the `tls:` key of the Ingress should not be rendered.

Don't render the `tls:` key of the Ingress when there are no secrets

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/templates/secrets.yaml

In the new version of external-secrets, the current default refreshInterval is causing a perpetual diff in ArgoCD.

Update default refreshInterval for external secrets

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/templates/deployment-celery.yaml
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/tests/ingress_test.yaml
charts/standard-application-stack/values.yaml

Change deprecated topologyKey from 'failure-domain.beta.kubernetes.io/zone' to 'topology.kubernetes.io/zone'

Cpt 974 topology spread zone deprecation

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/helpers/_ingress.yaml
charts/standard-application-stack/values.yaml

- `ingress.alb.scheme` value to allow for choice of `internet-facing` or `internal` alb
- updated `_ingress.yaml` helper to allow for generating internal lb class name

add option for internal alb

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/network-policy.yaml
charts/standard-application-stack/tests/networkpolicy_test.yaml

- Added `allow-aws-alb-internal-to-APP-NAME` NetworkPolicy for apps with an internal alb
- this allows apps in the same private subnet as the internal alb to send and recieve traffic from the alb

Added NetworkPolicy for apps with an internal alb

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/network-policy.yaml
charts/standard-application-stack/tests/networkpolicy_test.yaml

- Handle logic better around default-container port / oauthProxy port, and healthcheck port (multiple ports should be allowed)
- Avoid duplicate list of ports in ALB networkpolicy
- Re-factor code to avoid duplication 
- Adds extra tests for this (specifically testing port and subnets for public/internal schemes)

Fix logic around ALB NetworkPolicy and increase test-coverage

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_oauth-proxy.tpl
charts/standard-application-stack/tests/oauth2proxy_test.yaml
charts/standard-application-stack/values.yaml

oauth2proxy allows health check urls to be passed through to the upstream.
For example `$service/healthz` is allowed to pass through (without authentication).
However, previous to this fix, you could also access `$service/foo/healthz`.
This fix ensures that there's an exact match on the health check paths.

CPT-1074: Fixed oauthProxy regex for --skip-auth-regex paths

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/ingress.yaml
charts/standard-application-stack/tests/ingress_test.yaml

There's an ALB redirect in place (80->443).
We wish to maintain this behaviour because:
- It's still default browser setup
- Existing clients may be expecting this

CPT-1092: ALB Ingress should listen on port 80 as well

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/helpers/_workspace-output-secret.yaml
charts/terraform-cloud/templates/irsa-workspace.yaml
charts/terraform-cloud/templates/workspace.yaml
charts/terraform-cloud/tests/irsa_workspace_test.yaml
charts/terraform-cloud/tests/workspace_test.yaml
charts/terraform-cloud/values.yaml

- Shorten IRSA workspace names
- Remove hash trigger for IRSA as not needed with run triggers

- Auto add mntl- prefix to S3 bucket name if not added explicitly

---

charts/aws-api-gateway-operator/.helmignore
charts/aws-api-gateway-operator/CHANGELOG.md
charts/aws-api-gateway-operator/Chart.lock
charts/aws-api-gateway-operator/Chart.yaml
charts/aws-api-gateway-operator/README.md
charts/aws-api-gateway-operator/crds/crd-awsapigateways.yaml
charts/aws-api-gateway-operator/templates/NOTES.txt
charts/aws-api-gateway-operator/templates/_helpers.tpl
charts/aws-api-gateway-operator/templates/rbac.yaml
charts/aws-api-gateway-operator/tests/rbac_test.yaml
charts/aws-api-gateway-operator/values.yaml

add helm chart for `aws-api-gateway-operator`
this was tested on a local k3d cluster and worked successfully
this is a refactor of https://github.com/mintel/helm-charts/pull/134, which now uses the standard-application-stack helm chart as the basis for the app. This adds the CRD for the api gateways and cluster roles to watch for changes to resources created using that CRD.

add aws-api-gateway-operator helm chart

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/helpers/_workspace-output-secret.yaml
charts/terraform-cloud/templates/helpers/_workspace.yaml
charts/terraform-cloud/tests/workspace_test.yaml
charts/terraform-cloud/values.yaml

- Bump default s3, rds and opensearch versions to deliver new S3 versioning fix

Bump S3 refs:

---

charts/hybrid-consul-config-crds/Chart.yaml
charts/hybrid-consul-config-crds/README.md
charts/hybrid-consul-config-crds/templates/intention.yaml
charts/hybrid-consul-config-crds/templates/terminating-gateway.yaml

Mostly catches the limit of 63 chars - applies to `ServiceIntentions` and `TerminatinyGateways`

Fix k8s label / name restrictions

---

charts/basic-config/CHANGELOG.md
charts/basic-config/Chart.yaml
charts/basic-config/README.md
charts/basic-config/templates/service.yaml

Should reference the value under the `service` key rather than directly on `.Values`.

Fix basic-config service.selectorLabelsOverride reference

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/helpers/_deployment.yaml
charts/standard-application-stack/tests/deployment_lifecycle_test.yaml
charts/standard-application-stack/tests/ingress_test.yaml
charts/standard-application-stack/values.yaml

Nearly all our apps use AWS ALB instead of HAProxy, so make it the default
- Adjust unit-tests
- Added extra checks around lifecycle hook for ALB (make sure both ingress.enabled and ingress.alb.enabled are set)

Make AWS ALB the default Ingress

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/service.yaml
charts/standard-application-stack/tests/service_test.yaml

See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#ingress-annotations
Annotations on the `Service` have higher priority than on the `Ingress`. We cannot set the `Owner` label on the `Ingress` because that ends up adding it to the LB (which is a shared resource).
We can set the `Owner` tag on the `Service` which will propagate through to the `TargetGroup` (which is specific for each app). At this point we can scrape metrics which return the health of the `TargetGroup`, and provide access to the `Owner` label (via a join to `aws_applicationelb_info`)
---
Also added a bunch of `Service` tests.

Add support for ALB Service Owner annotation

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/templates/helpers/_pdb.yaml
charts/standard-application-stack/templates/pdbs.yaml
charts/standard-application-stack/tests/deployment_replicas_test.yaml
charts/standard-application-stack/tests/pdb_test.yaml

- Avoid setting `spec.replicas` when autoscaling is enabled (HPA manages this)
- Avoid creating a pod-disruption-budget when `autoscaling.minReplicaCount` < 2 (similar to `spec.replicas` behaviour)
- i.e. If there's only 1 pod, there's no point in having a PDB created
-  Introduced dedicated helper for this 
- Added extra tests
Previously the celery pdb enabling/disabling was also controlled by the main workloads `podDisruptionBudget.enabled` flag. 
Pretty sure this is a bug, so I've removed this.

Cpt 1530 handle pdb and replias when autoscaling

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/helpers/_ingress.yaml
charts/standard-application-stack/templates/keda-scaled-object.yaml
charts/standard-application-stack/tests/ingress_test.yaml
charts/standard-application-stack/tests/keda_scaled_object_test.yaml
charts/standard-application-stack/values.yaml
charts/terraform-cloud/README.md

- Added Keda `enableZeroReplicas` option
- Added Keda AWS trigger handling for `awsRegion` and `identityOwner` vars
- Avoids user having to specify AWS region/auth-modes (can override if required).
- Added Keda Prometheus trigger handling for `serverAddress`

Adding extra helpers for keda

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/templates/cronjobs.yaml
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/tests/service_test.yaml

This appears in every resource right now and makes code-reviews a struggle - it's probably still useful, so for now just keep it on main workloads (Deployment/Statefulset/Cronojbs)

INFRA-25882: Drop chart-version from most resources

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/helpers/_workspace.yaml
charts/terraform-cloud/templates/irsa-workspace.yaml
charts/terraform-cloud/templates/workspace.yaml
charts/terraform-cloud/tests/irsa_workspace_test.yaml
charts/terraform-cloud/tests/workspace_test.yaml
charts/terraform-cloud/values.yaml

Make syncWave per resource configurable (defaults remain the same).
- `syncWave` can be configured at either the `resourceCfg` or `instanceCfg` level.
- Ensure `syncWave` env-var is not passed through to tf-module when defined on the `instanceCfg`
- Added extra tests

INFRA-27862: Make argocd sync-wave configurable

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/templates/cronjobs.yaml
charts/standard-application-stack/templates/deployment-celery-beat.yaml
charts/standard-application-stack/templates/deployment-celery.yaml
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/tests/deployment_s3_enabled_test.yaml

- feat: Add helpers to generate terraform cloud secret names
- feat: Update deployment.yaml, deployment-celery-beat.yaml, deployment-celery.yaml to pass these secrets to envFrom for deployments
- test: Add test for new feature
- docs: Update CHANGELOG.md

Feat: Pass Terraform CLoud Helm chart secrets to deployments correctly

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/values.yaml

The OpenSearch Terraform module has a new patch version to fix a conflict in the Terraform AWS provider version constraints.
JIRA: INFRA-26627

Bump OpenSearch TF module version

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/tests/deployment_mariadb_enabled_test.yaml
charts/standard-application-stack/tests/deployment_s3_enabled_test.yaml

The Terraform resources created by the standard-application-stack Helm chart have a `secretNameOverride` value that can change the name of the Kubernetes secret the Terraform outputs get written to. The `mintel_common.tf_cloud_external_secrets` helper template was not respecting that value.

Fix Terraform secrets list to respect secretNameOverride

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/templates/helpers/_ingress.yaml
charts/standard-application-stack/templates/ingress-aws-es-proxy.yaml
charts/standard-application-stack/templates/network-policy-aws-es-proxy.yaml
charts/standard-application-stack/templates/role-aws-load-balancer-controller-okta.yaml
charts/standard-application-stack/templates/role-binding-aws-load-balancer-controller-okta.yaml
charts/standard-application-stack/templates/service-aws-es-proxy.yaml
charts/standard-application-stack/tests/opensearch_aws_es_proxy_test.yaml
charts/standard-application-stack/values.yaml

- Added `ingress.alb.okta` values used for Okta ALB authentication
- Added `opensearch.awsEsProxy.ingress` values to allow placing opensearch behind an ingress

add okta auth config to ingress and opensearch awsEsProxy ingress

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/tests/deployment_host_network_test.yaml
charts/standard-application-stack/values.yaml

A limitation with the AWS VPC CNI is that we have to put a webhook pod on the host's network to allow the EKS control plane to communicate with it.
This commit allows the pods of the main deployment to run on the host network so we can deploy webhooks with the standard-application-stack chart.

Allow using host network on main deployment

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_capabilities.tpl
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/templates/instrumentation.yaml
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/instrumentation_test.yaml
charts/standard-application-stack/values.yaml

This adds an [opentelemetry-operator Instrumentation](https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-auto-instrumentation-injection) custom resource to the standard-application-stack Helm chart. 
The instrumentation is enabled by default, but only to add OpenTelemetry environment variables to pods. If you also wanted to inject Python auto-instrumentation for example:
```yaml
---
otelInstrumentation:
injectPython:
enabled: true
````
JIRA: INFRA-28793

Add opentelemetry-operator Instrumentation custom resource

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/templates/configmaps.yaml
charts/standard-application-stack/templates/jobs.yaml
charts/standard-application-stack/templates/secrets.yaml
charts/standard-application-stack/templates/service-accounts.yaml
charts/standard-application-stack/tests/__snapshot__/configmaps_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/secret_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_account_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/configmaps_test.yaml
charts/standard-application-stack/tests/secret_test.yaml
charts/standard-application-stack/tests/service_account_test.yaml
charts/standard-application-stack/values.yaml

Sometimes we want jobs to run before the main workload but if those jobs require the same secrets, config maps or service accounts as the main workload then those also need to be synced at the same time as the job or it'll fail.

INFRA-29309: Add argocd annotation support to configmaps, secrets and service accounts

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/helpers/_ingress.yaml
charts/standard-application-stack/templates/ingress.yaml
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/ingress_test.yaml
charts/standard-application-stack/values.yaml

I had a problem where setting `ingress.extraIngresses.pathBasedRouting` was ignored because the extra ingresses would always use `ingress.pathBasedRouting`. This commit fixes that by allowing the extra ingresses to generically override any field of the top-level ingress i.e. the top-level ingress values are used as the defaults, which can be overridden.

Allow extraIngresses to override any field of the top-level ingress

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/deployment.yaml
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/deployment_env_test.yaml
charts/standard-application-stack/values.yaml

Various deployments are making use of `Values.env` , which means these envs can be duplicated across deployments and potentially containers.
The main examples is where we're using `Values.env` for both celery and the main-app deployment.
This MR introduces `Values.main.env` which is only applied the app-deployment's `main` container.

Added option to support custom env-vars that are only applied to the main app deployment/container.

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/helpers/_instrumentation.yaml
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/deployment_instrumentation_test.yaml

Grafana-agent uses prometheus-discovery to find pod information (based on IP matching).
It sometimes selects the wrong container-name if the app has sidecars. In our case, we only instrument the `main` container, so it's safe to force this value through.

INFRA-29953: Set container name in otel-resoruce-attributes

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/cronjobs.yaml
charts/standard-application-stack/templates/jobs.yaml
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/cronjob_test.yaml
charts/standard-application-stack/tests/jobs_test.yaml
charts/standard-application-stack/values.yaml

Cleanup old jobs using the new ttl option 
ref: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
By default this is applied to all cronjobs/jobs with a ttl of `60` seconds.
---
Changes:
- Added support to `.Values.cronjobs` (can be applied using `defaults` or per job)
- Added support to `.Values.jobs`
- Added cronjob tests
- Updated jobs tests
To disable this, the user can set `ttlSecondsAfterFinished: 0`

Infra 28274: Add cronjob ttl support

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace_output_secret_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap

GitHub was facing outages around the time mintel/helm-charts#270 was merged, meaning the releaser action never triggered.

Create no-op release of terraform-cloud chart to trigger chart releaser

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/ingress.yaml
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_stateful_set_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/values.yaml

- Added `blackbox.probeScheme` value to standard-application-stack chart
This will be used to specify an https scheme for some blackbox probe endpoints

[INFRA-27011] add `blackbox.probeScheme` value to standard-application-stack chart

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_stateful_set_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/values.yaml

Most services don't need this capability.

Remove the `NET_BIND_SERVICE` capability from default securityContext

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/helpers/_workspace-output-secret.yaml
charts/terraform-cloud/tests/__snapshot__/workspace_output_secret_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
charts/terraform-cloud/tests/workspace_output_secret_test.yaml
charts/terraform-cloud/tests/workspace_test.yaml

The v1alpha1 version of the external-secrets API has been deprecated since external-secrets v0.5.
See: https://external-secrets.io/latest/guides/v1beta1/

Upgrade external-secrets API version to v1beta1

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/_helpers.tpl
charts/terraform-cloud/templates/irsa-workspace.yaml
charts/terraform-cloud/templates/workspace.yaml
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
charts/terraform-cloud/tests/irsa_workspace_tags_test.yaml
charts/terraform-cloud/tests/irsa_workspace_test.yaml

- Modifies `Application` tag to be set from `global.application` but default to `global.name`
- Adds optional `Component` tag from `global.component`
- Updates the IRSA tag to use the same helper (means we can check for empty tag values)
- Adds specific unit-tests to test different use-cases around tags
- `Application` defaults to `global.name` unless set 
- `Component` is optional

Infra 31280 add reporting tags to workspace

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/irsa-workspace.yaml
charts/terraform-cloud/templates/workspace.yaml
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
charts/terraform-cloud/tests/irsa_workspace_tags_test.yaml
charts/terraform-cloud/tests/irsa_workspace_test.yaml
charts/terraform-cloud/tests/workspace_test.yaml

Initially this will generate duplicate application and component labels (both set to global.name) - but that's ok, as we'll adjust the application label on a per-app basis later.

INFRA-31280: Default component reporting label to name label

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/deployment-celery.yaml
charts/standard-application-stack/values.yaml

Support more timeout related options for celery - this is frequently timing out on some apps causing the health probes to fail.
In particular, the `ping` check supports a `--timeout` option that we should utilize.

Update healthchecks for celery and support `--timeout` option

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_labels_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_stateful_set_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/jobs_test.yaml
charts/standard-application-stack/values.yaml

We are adding a check to our pipeline to prevent anyone building and publishing an image with tag v0.0.0 so this mr is to simply make that the default.  This will mean that for new apps  argocd-image-updater cant release a new image to an app before a version above v0.0.0 is built.  This will prevent accidental releases.

update default standard-app-stack image tag to v0.0.0

---

.pre-commit-config.yaml
charts/basic-config/CHANGELOG.md
charts/basic-config/Chart.yaml
charts/basic-config/README.md
charts/basic-config/templates/service.yaml
charts/basic-config/tests/__snapshot__/service_test.yaml.snap

The default selector doesn't work because `toYaml {} => "{}"`, which is a non-empty string i.e. not a false-y value, so the `default` doesn't kick in.

Fix basic-config Service selector some more

---

charts/basic-config/CHANGELOG.md
charts/basic-config/Chart.yaml
charts/basic-config/README.md
charts/basic-config/templates/service.yaml
charts/basic-config/tests/__snapshot__/service_test.yaml.snap

`.Values.service.selectorLabelsOverride` is an object.
`(include "mintel_common.selectorLabels" .)` is a YAML string.
In order to not double-yaml encode the default selector labels, we have to first YAML-decode it.

basic-config: Fix obj vs string in Service template

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/keda-scaled-object.yaml
charts/standard-application-stack/tests/__snapshot__/keda_scaled_object_test.yaml.snap
charts/standard-application-stack/tests/keda_scaled_object_test.yaml
charts/standard-application-stack/values.yaml

Our default value for keda `fallback.replicas` might be too low for some apps.
It's safer to use `minReplicaCount` since that should be set on the min number of replicas that the site needs to meet it's SLA.

INFRA-33706: Keda should fallback to minReplicaCount 

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/tests/__snapshot__/keda_scaled_object_test.yaml.snap
charts/standard-application-stack/tests/keda_scaled_object_test.yaml
charts/standard-application-stack/values.yaml

For prometheus, this is no longer required from upstream. It's an internal to keda regardless.
This MR doesn't actually change functionality since it never validated what was specified under `metadata`... - but it does fix the docs :)

INFRA-33709: Remove Keda metricName from prometheus scaler (not used)

---

.tool-versions
charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/cronjobs.yaml
charts/standard-application-stack/templates/jobs.yaml
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/cronjob_test.yaml
charts/standard-application-stack/tests/jobs_test.yaml
charts/standard-application-stack/tests/vpa_test.yaml
charts/standard-application-stack/values.yaml

Long(ish) running Jobs are getting evicted frequently with karpenter - this mitigates against that.
Also required fix to work with latest `helm-unittest` (updates to `vpa_test.yaml`) - see https://github.com/helm-unittest/helm-unittest/releases/tag/v0.4.3

INFRA-34065: Add support for karpenter `do-not-disrupt` annotation on CronJobs/Jobs

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
charts/terraform-cloud/values.yaml

This bumps all the module versions as part of our work to upgrade to tf 1.3

tf 1.3 upgrade - bump all module versions in the terraform-cloud chart

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/_helpers.tpl
charts/terraform-cloud/templates/helpers/_module_v2.yaml
charts/terraform-cloud/templates/helpers/_workspace-v1.yaml
charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
charts/terraform-cloud/tests/__snapshot__/module-v2_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace-v2_test.yaml.snap
charts/terraform-cloud/tests/module-v2_test.yaml
charts/terraform-cloud/tests/workspace-v2_test.yaml
charts/terraform-cloud/values.yaml

The following variables have changed:
`allowDestroyPlan` renamed to `workspaceAllowDestroy` which is now the same as v1. We'll eventually rename this to `workspaceAllowDestroyPlan` which is more in sync with the upstream naming.
This now defaults to false in logs/prod accounts and is also configurable at the resource-config layer.
2. `destroyOnDeletion` renamed to `moduleDestroyOnDeletion` to make it clear it's related to modules. 
This now defaults to `true` which is inline with the `v1` operator.
3. `applyMethod` renamed to `workspaceApplyMethod` and now defaults to `auto` which is inline with v1 operator behavior.
4. Rename annotations helper and remove it from the Module - it only applies to the Workspace.

INFRA:5490: Ensure v2 handling of workspace-destroy flag is consistent with v1

---

charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/irsa-workspace.yaml
charts/terraform-cloud/templates/workspace.yaml

Support a temporary `operatorVersion: "migrate"` mode.
This will deploy the existing v1 Workspace resource along with the v2 Module resource.
This is currently being used to test whether we can simplify the migration process.

INFRA-35503: argocd support v2 tfc operator both versions

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/_helpers.tpl
charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
charts/terraform-cloud/tests/__snapshot__/workspace-v1_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace-v2_test.yaml.snap
charts/terraform-cloud/tests/workspace-v1_test.yaml
charts/terraform-cloud/tests/workspace-v2_test.yaml
charts/terraform-cloud/values.yaml

To configure the workspace _allow-destroy_ option...
In the v1 operator we rely on the `app.mintel.colm/terraform-allow-destroy`. This is picked up by a custom mintel operator which makes API calls to tf-cloud and adjusts the workspace.
In v2, there's a new `spec.allowDestroyPlan`.
I've re-factored the code to use the same shared function.
The previous function `mintel_common.terraform_cloud.allow_destroy_default` is renamed to `mintel_common.terraform_cloud.allow_destroy`, and is now used for setting both the annotation (used by our custom helper operator), as well as the new v2 `spec.allowDestroyPlan`.
Note, I've also reverted to use `hasKey`, because some of these values can be unset by the user (and they are not set in the helm chart value by default either).

INFRA-35710_fix: Update logic around default destroy option.

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
charts/terraform-cloud/tests/__snapshot__/irsa_workspace-v2_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/module-v2_test.yaml.snap
charts/terraform-cloud/tests/__snapshot__/workspace-v2_test.yaml.snap
charts/terraform-cloud/tests/workspace-v2_test.yaml

- Update v2 workspace to configure `spec.tags`
- Remove v2 workspace custom-extension annotations (will be handled by `spec.tags` and `spec.teamAccess`)

INFRA-35677: Update v2 workspace to handle spec.tags

---

charts/terraform-cloud/CHANGELOG.md
charts/terraform-cloud/Chart.yaml
charts/terraform-cloud/README.md
charts/terraform-cloud/values.yaml

Supports new cloudwatch alarms (requires >-tf 1.3)

INFRA-35724: Bump elasticache redis version

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/service.yaml
charts/standard-application-stack/tests/__snapshot__/service_test.yaml.snap
charts/standard-application-stack/tests/service_test.yaml

Allow the Application tag to be set on the underlying AWS TargetGroup resource.
I've made this optional a little more flexible since it will make the migration smoother (i.e. as we phase out Owner).

INFRA-37205: Allow Application tag to be set on Service

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/pod_monitor_test.yaml
charts/standard-application-stack/tests/service_monitor_test.yaml

Ensures that metric is available on the ingested metric.

INFRA-37110: Add `app.mintel.com/application` to `podTargetLabels

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/keda-scaled-object.yaml
charts/standard-application-stack/templates/vpa.yaml
charts/standard-application-stack/tests/__snapshot__/keda_scaled_object_constraints_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/keda_scaled_object_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/vpa_test.yaml.snap

Custom resouces should have the  `argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true` annotation so that ArgoCD will continue syncing other resources if the CRD for the custom resource is missing (such as during cluster bootstrapping).
JIRA: INFRA-38616

Add ArgoCD sync option to custom resources

---

.github/workflows/pull-request.yml
charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/pdbs.yaml
charts/standard-application-stack/tests/__snapshot__/pdb_test.yaml.snap
charts/standard-application-stack/tests/pdb_test.yaml
charts/standard-application-stack/values.yaml

The default value for `unhealthyPodEvictionPolicy` will be "AlwaysAllow", since most of our workloads deployed with this chart are stateless and it will prevent situations where Karpenter can't drain nodes because terminating an unhealthy pod would violate a PDB.
JIRA INFRA-39642

Add unhealthyPodEvictionPolicy the PDBs

---

charts/standard-application-stack/CHANGELOG.md
charts/standard-application-stack/Chart.yaml
charts/standard-application-stack/README.md
charts/standard-application-stack/templates/_helpers.tpl
charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_image_pull_secrets_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_labels_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/deployment_stateful_set_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/opensearch_aws_es_proxy_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
charts/standard-application-stack/tests/deployment_image_pull_secrets_test.yaml

Our default imagePullSecrets are now injected into pods by Kyverno. Remove them from the Helm chart.
JIRA: INFRA-38407

Remove default imagePullSecrets
