mintel/helm-charts

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/deployment.yaml
- charts/standard-application-stack/values.yaml
- feat: Add if statement to remove container ports if .Values.port = null
> Make Container Ports Optional:

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/values.yaml
> Disable datbase exporters by default since we already have cloudwatch

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/templates/ingress.yaml
- charts/standard-application-stack/values.yaml
- fix: Populate ingress manifest with extra annotations from values
- docs: Update CHANGELOG.md
> BUGFIX: Ingress Annotations

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_capabilities.tpl
- charts/standard-application-stack/templates/secrets.yaml
- charts/standard-application-stack/values.yaml
Replace deprecated KES objects with ESO objects
> Replace ExternalSecret objects

- .pre-commit-config.yaml
- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
Add (and run) helm-docs pre-commit hook (looks like it fixed the img tag on the readme too)
> Adding helm-docs pre-commit hook

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/ingress.yaml
Drop support for v1beta style ingresses (not supported by k8s 1.22)
> Removed support for Ingress v1beta1

- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/tests/workspace_test.yaml
- charts/terraform-cloud/values.yaml
- refactor: Use cluster-env-jsonnet to pass in agentPoolID
> Terraform Cloud helm chart

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
> Explicit IRSA workspace:

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_capabilities.tpl
- charts/standard-application-stack/templates/vpa.yaml
- charts/standard-application-stack/tests/vpa_test.yaml
- charts/standard-application-stack/values.yaml
This will give us resource request/limit recommendations.
> Add VerticalPodAutoscaler in recommendation-only mode

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/_helpers.tpl
- charts/terraform-cloud/templates/helpers/_workspace-output-secret.yaml
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/templates/irsa-workspace.yaml
- charts/terraform-cloud/templates/workspace-output-secret.yaml
- charts/terraform-cloud/templates/workspace.yaml
- charts/terraform-cloud/tests/workspace_test.yaml
- charts/terraform-cloud/values.yaml
- Setting environment based defaults for resources via helpers
> CPT-1129: Add Env Defaults to TF Cloud Chart

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/tests/workspace_test.yaml
- charts/terraform-cloud/values.yaml
- feat:Add ability to override workspace name
- docs: Update inline comments in values
> Add Workspace Name Override

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
> App IAM Opensearch bugfix:

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
- fix: Bump s3, mariadb, postgesql and opensearch default versions for versioning bugfix
> TF Cloud S3 bugfix

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/_helpers.tpl
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/templates/workspace-output-secret.yaml
- charts/terraform-cloud/templates/workspace.yaml
- charts/terraform-cloud/values.yaml
- Initial support for step-functions-eks module
- Ability to make external secret creation optional
- Add direct app.kubernetes.io/name label for workspaces to avoid overriding by wrappers
> TF Cloud Helm Step Support

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
- Bump default s3, rds and opensearch module versions to avoid S3 mfa_delete bug
> Bump S3 related modules

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_helpers.tpl
- charts/standard-application-stack/templates/cronjobs.yaml
- charts/standard-application-stack/templates/deployment-celery-beat.yaml
- charts/standard-application-stack/templates/deployment-celery.yaml
- charts/standard-application-stack/templates/deployment.yaml
- charts/standard-application-stack/values.yaml
Also includes a few formatting changes from pre-commit.
> CPT-633: Add event bus env vars derived from values

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/horizontal-pod-autoscaler.yaml
- charts/standard-application-stack/values.yaml
currently only scales on CPU or memory
> add horizontal-pod-autoscaler to standard application helm chart

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
Update TF Cloud module versions
> Update TF cloud module versions

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/workspace.yaml
- docs: Update CHANGELOG.md and README.md
> - fix: Give precedence to defaultVars over environment defaults

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
This version allows multiple statements in the inline and trust
policies.
> Update IAM role Terraform module version

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
Thia fixes a AWS provider version constraint problem.
> Update RDS Terraform module version

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
Also format some yaml apparently
> INFRA-27815: Update versions of modules which reference gruntwork modules

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
- feat: Bump version of S3 Terraform module to allow sftp access
> INFRA-28019: Add SFTP Option for S3 helm chart

- README.md
- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/helpers/_deployment.yaml
> Infra 27931: Fix ingress.alb.preStopDelay

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/tests/pod_monitor_test.yaml
- charts/standard-application-stack/tests/service_monitor_test.yaml
- charts/standard-application-stack/tests/service_test.yaml
Adding unit-tests for
- ServiceMonitors
- PodMonitors
- additionalMonitors
I've also added combined tests which test deployments / services (if applicable).
> INFRA-28288: Adding tests for ServiceMonitors and PodMonitors

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_capabilities.tpl
- charts/standard-application-stack/templates/jobs.yaml
- charts/standard-application-stack/tests/jobs_test.yaml
- charts/standard-application-stack/values.yaml
- Added template for `Job` resources, including config to support ArgoCD sync phases and waves.
> standard-application-stack: add template for Job resources

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/pod-monitor-celery.yaml
- charts/standard-application-stack/templates/pod-monitor-hybrid-consul.yaml
- charts/standard-application-stack/templates/service-monitor.yaml
- docs: Update README.md and CHANGELOG.md
> - fix: Use `deepCopy` function when creating new dict from values

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/_helpers.tpl
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/values.yaml
- docs: Update CHANGELOG.md and README.md
> - feat: Enable extra IAM

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/workspace_output_secret_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
- charts/terraform-cloud/values.yaml
- Update `opensearch` module to `v1.2.1`
> tf-cloud bump opensearch 1.2.1

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/service-accounts.yaml
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
To fix error:
```
YAML parse error on standard-application-stack/templates/service-accounts.yaml: error converting YAML to JSON: yaml: line 21: did not find expected key.
```
> Fixed serviceAccount.annotations issue

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/helpers/_ingress.yaml
- charts/standard-application-stack/templates/ingress.yaml
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
- charts/standard-application-stack/tests/ingress_test.yaml
The `ingress.extraIngresses` field was overriding the defaults from `ingress` quite right.
> Fix values/rendering around extraIngresses

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/deployment.yaml
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
See: https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> Replace `k8s.gcr.io` with `registry.k8s.io`

- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
- charts/standard-application-stack/tests/jobs_test.yaml
- charts/standard-application-stack/values.yaml
> INFRA-27592 Pinning semver for new apps

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/service.yaml
- charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_test.yaml.snap
- charts/standard-application-stack/tests/service_test.yaml
- charts/standard-application-stack/values.yaml
Allows us to specify specific port/target settings on the service.
> Support Service port/targetPort overrides

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/workspace_output_secret_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
- charts/terraform-cloud/values.yaml
- Bump api-gateway module to 0.3.2
> [INFRA-29655] bump api-gateway module to 0.3.2

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_dynamodb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_env_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_host_network_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_instrumentation_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_lifecycle_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_mariadb_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_memcached_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_ports_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_replicas_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_s3_enabled_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/deployment_stateful_set_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/ingress_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/pod_monitor_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
- charts/standard-application-stack/values.yaml
- Changed `blackbox.probeScheme` default value from `http` to `https`
> change blackbox exporter to https everywhere

- README.md
- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/templates/cronjobs.yaml
- charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
- charts/standard-application-stack/tests/cronjob_test.yaml
- charts/standard-application-stack/values.yaml
Allow cronjobs to be scheduled relative to a specific timezone.
> Allow CronJobs to specify timezone

- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/templates/cronjobs.yaml
- charts/standard-application-stack/templates/jobs.yaml
- charts/standard-application-stack/tests/__snapshot__/cronjob_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/service_monitor_test.yaml.snap
Removing duplicate securityContext annotation from job & cronjob
> INFRA-30727 securityContext dupe patch

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/tests/__snapshot__/opensearch_aws_es_proxy_test.yaml.snap
- charts/standard-application-stack/values.yaml
securityContext doesn't have an apparmor field.
> Remove apparmor field from securityContext of aws-es-proxy

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
Fixes an issue when using gp3 as the storage type (https://github.com/hashicorp/terraform-provider-aws/issues/28271)
> Bump RDS module version

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/mariadb_py_dba_test.yaml
- charts/standard-application-stack/values.yaml
- Added `extraUsers` for mariadb
> [INFRA-30570] add extraUsers for mariadb

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/templates/postgresql-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/postgresql_py_dba_test.yaml
- charts/standard-application-stack/values.yaml
- charts/terraform-cloud/README.md
- Added `extraUsers` for postgresql
Same as [this](https://github.com/mintel/helm-charts/pull/288), but for `postgres` instead of `mariadb`
> [INFRA-30573] add extraUsers for postgresql

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/templates/postgresql-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
- bump `py-dba` version to v0.1.3
> bump py-dba to 0.1.3

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/templates/postgresql-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
- Bugfix for py-dba when rds secret name is overridden
> Bugfix for py-dba when rds secret name is overridden

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/templates/irsa-workspace.yaml
- charts/terraform-cloud/templates/workspace.yaml
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
- charts/terraform-cloud/values.yaml
> Add tfcloud-auto-approver notifications to IRSA workspaces

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
- charts/terraform-cloud/values.yaml
Bump IRSA module version. Fixes an issue with duplicate SIDs being created for S3 buckets with mixed sources.
> Bump terraform-cloud IRSA module version

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_helpers.tpl
- charts/standard-application-stack/templates/cronjobs.yaml
- charts/standard-application-stack/templates/deployment.yaml
- charts/standard-application-stack/templates/helpers/_role.yaml
- charts/standard-application-stack/templates/helpers/_roleBinding.yaml
- charts/standard-application-stack/templates/helpers/_serviceAccount.yaml
- charts/standard-application-stack/templates/jobs.yaml
- charts/standard-application-stack/templates/role-aws-load-balancer-controller-okta.yaml
- charts/standard-application-stack/templates/role-binding-aws-load-balancer-controller-okta.yaml
- charts/standard-application-stack/templates/service-accounts.yaml
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/jobs_test.yaml
- charts/standard-application-stack/values.yaml
- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/_helpers.tpl
- charts/terraform-cloud/templates/irsa-workspace.yaml
- charts/terraform-cloud/values.yaml
See INFRA-30510 for background.
> INFRA-30510: Self-Contained Jobs

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/helpers/_keda.yaml
- charts/standard-application-stack/tests/keda_scaled_object_test.yaml
- charts/standard-application-stack/values.yaml
- Changed keda `maxReplicaCount` to 30
> increase keda maxReplicaCount to 30

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/templates/postgresql-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
- charts/standard-application-stack/values.yaml
- Bumped py-dba to `v0.2.0`
- Added `logLevel` variable to py-dba jobs
> bump py-dba version and set logLevel env var

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/_helpers.tpl
- charts/terraform-cloud/templates/helpers/_workspace.yaml
- charts/terraform-cloud/values.yaml
- Added support for `datasync` workspaces
> [INFRA-29866] terraform-cloud: add support for datasync workspaces

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_tags_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace_test.yaml.snap
- charts/terraform-cloud/tests/__snapshot__/workspace_test.yaml.snap
- charts/terraform-cloud/values.yaml
- feat: Bumped default terraform version to `1.2.9`
> - feat: Bumped rds related module versions to `1.3.0`

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/values.yaml
- Added comment to clarify CNAMEs for `ingress.extraHost` values.
> [INFRA-33499] add comment to clarify CNAMEs for  values

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
- charts/terraform-cloud/tests/__snapshot__/workspace-v2_test.yaml.snap
- charts/terraform-cloud/tests/workspace-v2_test.yaml
- charts/terraform-cloud/values.yaml
Allow changing the allowDestroyPlan and applyMethod for all Workspaces at a global level.
JIRA: INFRA-35710
> terraform-cloud: add globals for allowDestroyPlan and applyMethod

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
- charts/terraform-cloud/tests/__snapshot__/irsa_workspace-v2_test.yaml.snap
- charts/terraform-cloud/tests/irsa_workspace-v2_test.yaml
- charts/terraform-cloud/tests/workspace-v1_test.yaml
- charts/terraform-cloud/tests/workspace-v2_test.yaml
It was calling the v1 version since I had duplicated the function name.
> INFRA-35656: Fix call to runTriggers for operator-v2 

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/templates/helpers/_workspace-v2.yaml
- charts/terraform-cloud/tests/__snapshot__/workspace-v2_test.yaml.snap
- charts/terraform-cloud/tests/workspace-v2_test.yaml
- charts/terraform-cloud/values.yaml
Adds option to populate `teamAccess` on the new v2 workspace.
> Infra 35677 tfc v2 add team access support

- charts/terraform-cloud/CHANGELOG.md
- charts/terraform-cloud/Chart.yaml
- charts/terraform-cloud/README.md
- charts/terraform-cloud/values.yaml
Bump elasticache module versions to:
Update default redis version to 7.1
Update default memcached version to 1.6.22
> Bump elasticache module versions

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/_oauth-proxy.tpl
- charts/standard-application-stack/templates/mariadb-py-dba.yaml
- charts/standard-application-stack/templates/postgresql-py-dba.yaml
- charts/standard-application-stack/tests/__snapshot__/jobs_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/mariadb_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/oauth2proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/opensearch_aws_es_proxy_test.yaml.snap
- charts/standard-application-stack/tests/__snapshot__/postgresql_py_dba_test.yaml.snap
- charts/standard-application-stack/tests/jobs_test.yaml
- charts/standard-application-stack/values.yaml
We working on removing CPU limits from containers.
JIRA: INFRA-37596
> Remove default CPU limits for containers

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/tests/__snapshot__/opensearch_aws_es_proxy_test.yaml.snap
- charts/standard-application-stack/values.yaml
Reduce the default CPU requests for database clients, exporters, etc.
JIRA: INFRA-37597
> Reduce default CPU requests

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/deployment-mysqlclient.yaml
- charts/standard-application-stack/templates/deployment-postgresqlclient.yaml
Changes the default images for psql/mysql client helps to the new ones in our ECR repo.
> Infra 30645: update rds helpers repo

- charts/standard-application-stack/CHANGELOG.md
- charts/standard-application-stack/Chart.yaml
- charts/standard-application-stack/README.md
- charts/standard-application-stack/templates/entra-service-principal.yaml
- charts/standard-application-stack/tests/entra_test.yaml
- charts/standard-application-stack/values.yaml
Expose the following options on the Entra `ServicePrincipal` resource
- appRoleAssignmentRequired (default true)
- visibleToUsers (default true)
> Expose additional options on the Entra ServicePrincipal resource
